local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Streke", "Midnight")
local Tab = Window:NewTab("ادوات مفيده")
local Section = Tab:NewSection("ادوات مفيده")
Section:NewButton("طيران& ادمن", "ButtonInfo", function()
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Gui-Fly-v3-37111"))() loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
    print("Clicked")
end)

local Tab = Window:NewTab("تحولات تظهر للناس")
local Section = Tab:NewSection("تحولات")
Section:NewButton("تحول scp096"), "ButtonInfo", function()
        loadstring(game:HttpGet("https://pastefy.app/YsJgITXR/raw"))()
    end)
